baseURL = "http://micropropro.com/"
languageCode = "en-us"
title = "Tufts ME 193: MPP"
theme = "book"
enableGitInfo = true
[params]
  BookSection = '*'
  BookRepo = 'https://github.com/pingswept/micropropro'
  BookEditPath = 'edit/master/content'
[markup.goldmark.renderer]
  unsafe= true
